# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG (opensource@telekom.de)

# SPDX-License-Identifier: Apache-2.0

blank_issues_enabled: true
contact_links:
  - name: 🤔 Ask a Question
    url: 'https://github.com/telekom/wurzel/discussions/new?category=question'
    about: Ask a question about how to use Wurzel using GitHub discussions
