# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG
#
# SPDX-License-Identifier: CC0-1.0

services:
  wurzel-pipeline: # this is the main Dockerfile for the Wurzel pipeline
   # ghcr.io/telekom/wurzel:latest
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=3.11
    container_name: wurzel-demo
    environment:
      - MANUALMARKDOWNSTEP__FOLDER_PATH=/usr/app/demo-data
      - WURZEL_PIPELINE=pipelinedemo:pipeline
    working_dir: /usr/app
    volumes:
      - ./demo-data:/usr/app/demo-data:ro
      - ./pipelinedemo.py:/usr/app/pipelinedemo.py:ro
      - ./output:/usr/app/data
    command: ["./entrypoint.sh"]


# run with `docker-compose up --build`
