# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG
#
# SPDX-License-Identifier: CC0-1.0

version: '3.8'

services:
  wurzel-pipeline:
    build:
      context: ../../
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
      args:
        - PYTHON_VERSION=3.11
    image: test_wurzel
    container_name: wurzel-demo
    environment:
      - MANUALMARKDOWNSTEP__FOLDER_PATH=/usr/app/demo-data
      - WURZEL_PIPELINE=pipelinedemo:pipeline
      - GIT_USER=wurzel-demo
      - GIT_MAIL=demo@example.com
      - DVC_DATA_PATH=/usr/app/dvc-data
      - DVC_FILE=/usr/app/dvc.yaml
    volumes:
      - ./demo-data:/usr/app/demo-data:ro
      - ./pipelinedemo.py:/usr/app/pipelinedemo.py:ro
      - ./output:/usr/app/output
    working_dir: /usr/app
    command: ["sh", "-c", "/bin/bash ./entrypoint.sh"]

  # Optional: Example service for extending the pipeline
  wurzel-pipeline-extended:
    extends: wurzel-pipeline
    container_name: wurzel-demo-extended
    environment:
      - MANUALMARKDOWNSTEP__FOLDER_PATH=/usr/app/demo-data
      - WURZEL_PIPELINE=pipelinedemo:pipeline
    profiles:
      - extended
