# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG
#
# SPDX-License-Identifier: CC0-1.0

services:
  wurzel-pipeline: # this is the main Dockerfile for the Wurzel pipeline
   # ghcr.io/telekom/wurzel:latest
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=3.11
    image: test_wurzel
    container_name: wurzel-demo
    environment:
      - GIT_USER=wurzel-demo
      - GIT_MAIL=demo@example.com
      - DVC_DATA_PATH=/app/data
      - DVC_FILE=/app/dvc.yaml
    working_dir: /app
    command: ["./entrypoint.sh"]

  wurzel-pipeline-extended:
    extends: wurzel-pipeline
    container_name: wurzel-demo-extended
    environment:
      - MANUALMARKDOWNSTEP__FOLDER_PATH=/app/demo-data
      - WURZEL_PIPELINE=pipelinedemo:pipeline
    volumes:
      - ./demo-data:/app/demo-data:ro
      - ./pipelinedemo.py:/app/pipelinedemo.py:ro
      - ./output:/app/data
    profiles:
      - extended
# run with `docker-compose --profile extended up`
